import * as settings from '../sections/settings'
import * as derivatives from './derivatives'

const {
    version,
    versionKey,
    dealAmount,
    instructionTimeout, 
    dealTimeout,
    moveAmountMin,
    moveAmountMax,
    moveAmountStep,
    durationMin,
    durationMax,
    durationStep,
    vignetteVariantKey,
    backgroundColorKey,
    backgroundColorDefault,
    levelKey,
    levelDefault,
    ignoreInstructionKey,
    durationKey,
    durationDefault,
    moveAmountKey,
    moveAmountDefault,
    achievementsKey,
    achievements, 
    movesAmount, 
    duration, 
    ignoreInstruction, 
    backgroundColor, 
    vignetteVariant, 
    level
} = settings

const {
    flow,
    deal,
    alert,
    moves,
    role,
    stage,
    elapsed,
    elapsedWithUnits,
    levelDescription,
    scores,
    reversed,
    scoresSlashed,
    scoresVerbose,
    isFullfilled,
    progress,
    levelClass,
    levelNumber
} = derivatives

export { 
    version,
    versionKey,
    dealAmount,
    instructionTimeout, 
    dealTimeout,
    moveAmountMin,
    moveAmountMax,
    moveAmountStep,
    durationMin,
    durationMax,
    durationStep,
    vignetteVariantKey,
    backgroundColorKey,
    backgroundColorDefault,
    levelKey,
    levelDefault,
    ignoreInstructionKey,
    durationKey,
    durationDefault,
    moveAmountKey,
    moveAmountDefault,
    achievementsKey,
    achievements, 
    movesAmount, 
    duration, 
    ignoreInstruction, 
    backgroundColor, 
    vignetteVariant, 
    level,
    flow,
    deal,
    alert,
    moves,
    role,
    stage,
    elapsed,
    elapsedWithUnits,
    levelDescription,
    scores,
    reversed,
    scoresSlashed,
    scoresVerbose,
    isFullfilled,
    progress,
    levelClass,
    levelNumber
}
